service: api-with-auth

custom:
  secrets: ${file(secrets.json)}


provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  timeout: 30
  region: us-east-1
  environment:
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    DB_USERNAME: ${self:custom.secrets.DB_USERNAME}
    DB_PASSOWRD: ${self:custom.secrets.DB_PASSOWRD}
    DATABASE: ${self:custom.secrets.DATABASE}
    DB_HOST: ${self:custom.secrets.DB_HOST}

functions:
  verify-token:
    handler: controllers/VerifyToken.auth

  login:
    handler: controllers/AuthHandler.login
    events:
      - http:
          path: login
          method: post
          cors: true

  register:
    handler: controllers/AuthHandler.register
    events:
      - http:
          path: register
          method: post
          cors: true

  me:
    handler: controllers/AuthHandler.userDetails
    events:
      - http:
          path: profile
          method: get
          cors: true
          authorizer: verify-token

  getUsers:
    handler: controllers/UserHandler.getUsers
    events:
      - http:
          path: users
          method: get
          cors: true
          authorizer: verify-token
 
  getQuiz:
    handler: controllers/QuizHandler.getQuiz
    events:
      - http:
          path: quiz
          method: get
          cors: true
          authorizer: verify-token
 
  creteQuiz:
    handler: controllers/QuizHandler.createQuiz
    events:
      - http:
          path: quiz
          method: post
          cors: true
          authorizer: verify-token
 
  creteQuestion:
    handler: controllers/QuestionHandler.createQuestion
    events:
      - http:
          path: question
          method: post
          cors: true
          authorizer: verify-token
  
  saveQuizQuestion:
    handler: controllers/QuizHandler.saveQuizAnswer
    events:
      - http:
          path: quiz/answer
          method: post
          cors: true
          authorizer: verify-token
  
  startQuiz:
    handler: controllers/QuizHandler.startQuiz
    events:
      - http:
          path: quiz/start/{id}
          method: get
          cors: true
          authorizer: verify-token
          request: 
            parameters: 
              paths: 
                id: true

  # getQuestion:
  #   handler: controllers/QuestionHandler.getQuestion
  #   events:
  #     - http:
  #         path: question/{id}
  #         method: get
  #         cors: true
  #         authorizer: verify-token
  #         request: 
  #           parameters: 
  #             paths: 
  #               id: true


plugins:
  - serverless-offline